### ISSUE TITLE
logとerror logの爆発

### ISSUE THREAD

**Issue by darallium** [guest-nico/nicoLiveCheckTool#11]
logとerrorlog.txtが爆発しています。二つを足して177gbを占拠しています。
共有する手段があれば共有しますが、どうでしょう？

![EbXryda 1](https://user-images.githubusercontent.com/46854880/162435475-74c15339-b267-4df4-b9ac-6ba7d96ba739.png)

**Comment by darallium** [comment]
errorlog.txtはこれが飽和しているようです

`には21:34:32` 0 message リモート サーバーがエラーを返しました: (404) 見つかりません
source System
stacktrace    場所 System.Net.HttpWebRequest.GetResponse()
 targetsite System.Net.WebResponse GetResponse()`

**Comment by guest-nico** [comment]
ご不便をおかけしてしまい申し訳ありません。「放送中」タブの更新時、コミュニティサムネイルが設定されていない放送を表示しようとするとそのようなログが出力されているようでした。ご指摘の通り、「オプション」の「一般」タブの「ログをファイルに出力する」設定をオンにしていると細かな動作等が記録されていることでファイルサイズが肥大してしまうことが考えられるかと思います。サイズが大きくなってしまっている場合、お手数をおかけしてしまい申し訳ありませんが、ログファイルを削除していただいたり設定をオフにしていただくことになってしまうかと思います。
使いづらい設定となってしまっており申し訳ありません。

**Comment by darallium** [comment]
ご対応頂きありがとうございます。注意書きがあるにもかかわらずこちらの設定ミスでこのようなIssueを投げてしまい申し訳ございません。幸運にもサムネイルの設定されていない方の画像に対して大量にリクエストが放出されていたというバグが発見されていて良かったです。お手数をおかけしまして申し訳ありませんでした。

**Comment by guest-nico** [comment]
ご報告いただきありがとうございます。分かりづらい設定となってしまっており申し訳ありませんでした。サムネイルが設定されていない放送につきましては、現状では取得を試みるまでは判別が難しいかもしれません。ご指摘の通り、接続をする前に判別ができますと通信量を減らすことにもなるかと思いますので、何か方法が見つかりましたら改善をしてみたいと思います。ご不便をおかけしてしまい申し訳ありませんでした。
