### ISSUE TITLE
ニコ生サーバー仕様変更の件

### ISSUE THREAD

**Issue by nnn-revo2012** [guest-nico/nicoLiveCheckTool#17]
.NET4.0版のチェックツールが動作しない件ですが、Program.csの以下の３行を
```
			#if !NET40
				ServicePointManager.SecurityProtocol = SecurityProtocolType.Ssl3 | SecurityProtocolType.Tls |SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;
			#endif
```
を以下の１行にすればよくないですか？（.NET4.5でコンパイル通るのは確認してます）
```
                    ServicePointManager.SecurityProtocol = SecurityProtocolType.Ssl3 | 
SecurityProtocolType.Tls | (SecurityProtocolType)0x00000C00 |  (SecurityProtocolType)0x00000300;
```
それと視聴プラグインにも念のためProgram.csに以下の１行入れといた方が良いと思います。

				ServicePointManager.SecurityProtocol = SecurityProtocolType.Ssl3 | SecurityProtocolType.Tls |SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;

**Comment by guest-nico** [comment]
ご指摘をいただきありがとうございます。チェックツールの.NET4.0版で接続できなくなっていた現象につきまして、ご指摘いただきました箇所が問題であったことが考えられるかと思います。ver0.1.7.117(https://github.com/guest-nico/nicoLiveCheckTool/commit/4f6a69bed8398a751f249c1be9b93bf065a5e612 )にて修正いたしました。
視聴プラグインにつきましても、https://github.com/guest-nico/ncvPlayPlugin/commit/e156301511e97f870123b71bea049535420de2c1  にて修正させていただきました。貴重なご指摘をいただき感謝いたしております。

**Comment by nnn-revo2012** [comment]
すみません。コミュ掲示板の状況だとXPだとServicePointManager.SecurityProtocol ... のところでエラーになってるっぽいですね。

1. XP（＆VISTA）は基本TLS1.0まで (つまりOSがサポートしてないのでエラー)
2. firefoxやChromeはプログラムでTLS1.2をサポートしてる（今XP使ってる人はこの状態）
3. TLS1.2更新プログラムとかあるようだがあまりお勧めできない（難しすぎる）
   （XP TLS1.2 でググってみるとやり方が出てきます）

ですので.NET4.0版は``#if !NET40``のところ元に戻してlive.nicovideo.jpにアクセスするところを全てCurlを使うという方法でやるしかないんじゃないでしょうか。
結局お力になれないようですみませんでした。

**Comment by nnn-revo2012** [comment]
>.NET4.0版は#if !NET40のところ元に戻してlive.nicovideo.jpにアクセスするところを全てCurlを使うという方法でやるしかないんじゃないでしょうか。

1.7.117の新ライブラリー版がlibcurl版なんですね。それの.net4.0版の#if !NET40のところを元に戻したものはおそらくXPで動作すると思います。

**Comment by nnn-revo2012** [comment]
Windows7はWindowsUpdateの状況によりTLS1.2がインストールされてない場合があるようです。
Windows7(SP1)の場合はWindowsUpdateでKB3140245が適用されているか調べて、もしない場合は以下の手順でKB3140245とEasyfix(TLS1.2有効化)を適用しないとだめなようです。

https://acceltools.com/info/windows7-enable-tls-1-2/

**Comment by guest-nico** [comment]
情報をいただきありがとうございます。ご指摘の通り、XPにつきましてはCurlを使用するのが有効かと思います。また、Windows7につきましても、TLS1.2に関してそのようにお伝えさせていただければと思います。一先ず、動作できる状態となるよう改善させていただきたいと考えております。詳しいご知見をいただき感謝いたします。

**Comment by nnn-revo2012** [comment]
コミュ掲示板3335の件
C#でusing()で囲ってHttpClient()を使ってると「大量の読み込みで使用可能なソケットの数が枯渇します。」となるのですが、どこかで頻繁にHttpClient()を呼んでませんか？
その場合HttpClient()じゃなくて HttpWebRequest か WebClient を使ってください。
ただし、頻繁にHttpClient()を呼ばなければ問題は起きません。
詳しくは httpclient using でググってみてください。

また、上記の件がlibcurlを呼ぶことで起こってるならlibcurlでメモリー解放かリソースの解放がされてないのかもしれません。libcurlがHttpClient()と同じ仕様かどうかはわからないのですが、問題あるようならその辺を中心に調べてみるとよいと思います。

**Comment by guest-nico** [comment]
ご指摘をいただきありがとうございます。
HttpClientにつきましては、ご指摘の通り、一部で使用してしまっておりました。コミュニティ掲示板3351のテスト版では使用する頻度が比較的高いと思われる箇所を修正しております。
libcurlにつきましても、ご指摘の通り、リソースの解放に問題があった可能性が考えられるかと思います。連続で使用した際にメモリの使用量が大きくなってしまう現象を手元で確認し、ver0.1.7.118にて修正してみました。こちらの修正の際にソケットにつきましても改善されておりましたら幸いです。
まだ原因を掴めていないところもありますが、なるべく改善できるよう努めてまいりたいと考えております。

**Comment by nnn-revo2012** [comment]
もう大丈夫そうなのでcloseします。

**Comment by guest-nico** [comment]
ご指摘いただき感謝いたします。教えていただきました点に注意しつつ修正してまいりたいと思います。
