### ISSUE TITLE
.net4.5版の配布ZIP内のSQLite.dllの件

### ISSUE THREAD

**Issue by nnn-revo2012** [guest-nico/nicoLiveCheckTool#18]
チェックツール.net4.5版の配布ZIPの中のSQLite.dllだけversion1.0.104.0なので録画ツールやチェックツール.net4.0などのdllやexe.configなどと比較してみたのですが、チェックツール.net4.5版だけSQLite.dllが1.0.104.0でないとだめなのか原因がわかりました。

現状だと配布ZIPの中の.net4.5版の ニコ生放送チェックツール（仮.exe.config にbindingRedirect の項目がないのが原因と思われます。
ここで ``<bindingRedirect oldVersion="0.0.0.0-1.0.108.0" newVersion="1.0.108.0" /> ``を指定しないと現行のCookieGetterがversion1.0.104.0のSQLiteを探して使うようです。

- bindingRedirectに1.0.108.0を指定しているのに1.0.104.0のSQLiteしかないとCookieGetterが1.0.108.0のSQLiteを探してエラーになる。（これはコミュ掲示板3388で僕(CNq3tIeWYF)が報告した件でもあります）
- bindingRedirect指定なしで1.0.104.0以外のSQLiteしかないとCookieGetterが1.0.104.0のSQLiteを探してないためエラーになる。

ですので、すぐじゃなくてもいいですが以下の2ファイルを同時に変更お願いいたします。
- ニコ生放送チェックツール（仮 配布ZIPの中の.net4.5版の ニコ生放送チェックツール（仮.exe.config にbindingRedirectを指定する。
  （おそらくguest-nicoさんのチェックツールの開発環境上の bin/Release の中の ニコ生放送チェックツール（仮.exe.config にSQLite.dllのbindingRedirectがついていると思いますのでそのファイルをそのまま使ってください。）
- ニコ生放送チェックツール（仮 配布ZIPの中の.net4.5版のSQLite.dllをニコ生新配信録画ツール（仮 配布ZIP中のSQLite.dllに入れ替える。
  録画ツール（仮 配布中のSQLite.dllは1.0.108.0 net451版です。チェックツール.net4.5版もプログラム上（System.Data.SQLiteの参照プロパティ）も1.0.108.0 net451版がPATH指定されていることは確認済みです。
```
SHA1 ハッシュ (対象 D:\home\tmp\（仮 ver0.88.75&0.1.3.10.76\System.Data.SQLite.dll):
a7366aaac7c85a9f2f395bf283f4a04ed3547475
```
一応上記2ファイルをzipにまとめて添付しておきます。[net45_modify.zip](https://github.com/guest-nico/nicoLiveCheckTool/files/12194923/net45_modify.zip)

また.net4.0版チェックツール、録画＆登録ツール、視聴プラグインはexe.configにbindingRedirect指定されており、同梱のSQLite.dllも 1.0.108.0 なので問題ありません。

**Comment by guest-nico** [comment]
ご指摘いただきありがとうございます。確認いたしましたところ、ご指摘の通り、チェックツールの.NET4.5版ではバージョンが1.0.104.0となってしまっており、ニコ生放送チェックツール（仮.exe.configはそのような記述になってしまっておりました。チェックツールのver0.1.7.120 debug3版よりそのように修正させていただいております。ご指摘いただいていた問題の原因に気づくことができず申し訳ありませんでした。詳しいご報告をいただき感謝いたします。

**Comment by nnn-revo2012** [comment]
ver0.1.7.120 debug3版で変更の確認および動作確認いたしました（オプションのアカウント設定でブラウザ一覧が正常に表示できること）
ありがとうございます。

**Comment by guest-nico** [comment]
ご報告いただきありがとうございます。改善されており良かったです。また何かありましたらご連絡いただけましたら幸いです。
