### ISSUE TITLE
SnkLib.App.CookieGetterの新旧バージョンがコンフリクト？

### ISSUE THREAD

**Issue by nnn-revo2012** [guest-nico/nicoLiveCheckTool#2]
*.csproj上でSnkLib.App.CookieGetterの新旧バージョンがコンフリクトしてませんか？
SharpDevelopでコンパイルしてみるとコンパイル時エラーになるのでプロジェクトcheck tool 4.0のSnkLib.App.CookieGetter2.3.1とforms1.4.0をアンインストールしてからSnkLib.App.CookieGetterを入れ直してください。
VS2012以降をお持ちでしたらパッケージマネージャーコンソールでやるのが簡単で確実かと思います（たぶんお持ちですよね？）
もし、ローカル側では解決している問題でしたらすみません。

パッケージのインストールはプロジェクト毎(check tool 4.0 と check tool 4.5.2)それぞれにやらないとうまくいかないと思います(特にプロジェクト間で.NETのバージョンが違う場合)

パッケージマネージャーコンソールだとこんな感じになります。
1,右上の「既定のプロジェクト」をcheck tool 4.0
2.PM> Install-Package SnkLib.App.CookieGetter -Version 2.4.0
3.PM> Install-Package SnkLib.App.CookieGetter.forms -Version 1.4.1
4.右上の「既定のプロジェクト」をcheck tool 4.5.2
5.PM> Install-Package SnkLib.App.CookieGetter -Version 2.4.0
6.PM> Install-Package SnkLib.App.CookieGetter.forms -Version 1.4.1
こんな感じになります。Nuget CLIだとpackage.configや*.csprojは変更しないようなのでうまくいかないです。

**Comment by nnn-revo2012** [comment]
念のため当方で作成したnugetファイルを置いときます。

https://github.com/nnn-revo2012/SnkLib.App.CookieGetter/releases/tag/v2.4.0

**Comment by guest-nico** [comment]
ご返信が遅れてしまい申し訳ありませんでした。
申し訳ありません、こちらでnicoLiveCheckToolをcloneし、SharpDevelop4.4.2で
ビルドしてみたところ、こちらの環境ではSnkLib.App.CookieGetterについては警告やエラーは
出ていないようでしたが、check tool 4.0.csprojでは一部SnkLib.App.CookieGetter2.3.1.0が
参照されていたようでしたので、パッケージマネージャーコンソールから
SnkLib.App.CookieGetter2.4.0.0とSnkLib.App.CookieGetter.forms1.4.1.0を
インストールしてみました。

また、ビルド時にInterop.IWshRuntimeLibrary.dllと
署名つきのNAudioが見つからないというエラーが出ておりましたので、
この二つはpackagesフォルダに置いてみました。

手元でcloneして試してみたところでは、SharpDevelop4.4.2とVisualStudio2017では
パッケージの取得後にビルドが通るようになったのではないかと思いますが、改善されているでしょうか？

**Comment by nnn-revo2012** [comment]
修正ありがとうございます。正常にビルドできるようになりました（SharpDevelop4.4.2とVisual Studio Express 2015 for Windows Desktopで確認）

それとcheck tool 4.5.2の参照リンクなのですが、4.0用のライブラリーが混じってますので参照リンクを削除しておいた方がいいと思います。
ver0.1.7.63(9fe6243b23c3568f86120fbc32bd86c7d46eb260)の時のcheck tool 4.5.2の参照リンクには存在していませんでした（以下の赤枠のリンク６つです）。

![checktool45link](https://user-images.githubusercontent.com/45882358/80187521-bde7ac00-864a-11ea-8fe6-eba544ee6c48.png)

**Comment by guest-nico** [comment]
ご報告ありがとうございます。正常にビルドができるようになっていて良かったです。
度々お手数をおかけしてしまい申し訳ありません。
https://github.com/guest-nico/nicoLiveCheckTool/commit/15f29b91180c79e11f507165427bf34a30085671 で参照を削除致しました。
詳しいご指摘をいただき感謝致します。

**Comment by nnn-revo2012** [comment]
修正ありがとうございます。
SnkLib.App.CookieGetterのエラーは .gitignore で SnkLib.App.CookieGetter.2.4.0.0/**/x86 がなかったためのようですね。
 .gitignore に関しては nicoNewStreamRecorderKakkoKari の方も同様なのでお時間のある時に変更いただければと思います。

本件自体は解決いたしましたので、このissueは数日で閉じたいと思います。

!nicoNewStreamRecorderKakkoKari/packages/WebSocket4Net.0.15.2/
!nicoNewStreamRecorderKakkoKari/packages/SnkLib.App.CookieGetter.2.4.0.0/
!nicoNewStreamRecorderKakkoKari/packages/SnkLib.App.CookieGetter.Forms.1.4.1.0/
!nicoNewStreamRecorderKakkoKari/packages/NAudio.1.8.5/
!nicoNewStreamRecorderKakkoKari/packages/RtmpSharp2.dll
!nicoNewStreamRecorderKakkoKari/packages/SnkLib.App.CookieGetter.2.4.0.0/**/x86

**Comment by guest-nico** [comment]
ご指摘をいただきありがとうございます。
こちらでも確認したところ、ご指摘の通り、.gitignoreに
SnkLib.App.CookieGetter.2.4.0.0/**/x86がなかったことが原因のようでした。
こちらでエラーが出なかったのはcheck tool 4.0.csprojにはver2.3.1.0の
SnkLib.App.CookieGetter.targetsへの参照が残っており、
packages.configにもver2.3.1.0が残っていたために、SharpDevelopで
Restore Packagesを実行した際にver2.3.1.0の
build/net40/x86/SnkLib.App.CookieGetter.x86Proxy.exeが
配置されてしまいエラーが出ていなかったようでした。
ライブラリの移行にあたり確認が不足しておりました。

nicoNewStreamRecorderKakkoKariのほうも
https://github.com/guest-nico/nicoNewStreamRecorderKakkoKari/commit/6c61d18770a916208cda5ab8035fd8ca291551f4 にて修正致しました。
何度もお手数をおかけしてしまい申し訳ありませんでした。
プロジェクトの管理など不備も多く非常に助かります。
なるべく気をつけて更新していきたいと思いますが、もし問題などありましたら
ご指導いただければ幸いです。

**Comment by nnn-revo2012** [comment]
nicoNewStreamRecorderKakkoKariの方もx86フォルダーが出来てコンパイル時にエラーが出ないことを確認しました。ありがとうございます。
