### ISSUE TITLE
util/util.csのエンコードについて

### ISSUE THREAD

**Issue by nnn-revo2012** [guest-nico/nicoLiveCheckTool#4]
util/util.csのファイルのエンコードがシフトJISになっています。
シフトJIS関連の関数かメソッドでシフトJISの文字列が埋め込まれてるのなら必要かもしれませんが、ソースをざっと見た限りそういうところは見受けられないのでutil.cs自体をテキストエディターでUTF-8(BOMあり)で保存し直したほうがよいのではないでしょうか？

録画ツール(仮や視聴プラグインも同じだと思いますが、まあＶＳはシフトJISでもUTF-8でも問題なくコンパイルできるかと思いますんで問題ないようであれば各ソフトの次のバージョンアップで対応していただければよいかと思います。

**Comment by guest-nico** [comment]
エンコードの不備があり申し訳ありませんでした。
チェックツールのhttps://github.com/guest-nico/nicoLiveCheckTool/commit/cf1d477d6618bfdc01fe1c7fb0d5a3ac021e1445 、録画ツールのhttps://github.com/guest-nico/nicoNewStreamRecorderKakkoKari/commit/1eaba0c052391f628b06f2444499913abc644fdd  、視聴ツールのhttps://github.com/guest-nico/ncvPlayPlugin/commit/6d83779b7032338c7a9705ca5fb1a4090040bd98 にてエンコードをUTF-8のBOMありに修正しております。ご指摘いただきありがとうございます。

**Comment by nnn-revo2012** [comment]
チェックツール、新配信録画ツール、視聴ツールは確認いたしました。
録画登録ツールの方のutil/util.csがシフトJISのままのようです。お手数ですがご確認お願いいたします。

**Comment by guest-nico** [comment]
修正が漏れており申し訳ありませんでした。https://github.com/guest-nico/nicoNewStreamRecorderKakkoKari/commit/ec28e92b03f3ee959b519dba901348f67842cd0c にて録画登録ツールのutil/util.csを修正いたしました。お手数おかけしてしまい申し訳ありません。ご指摘いただきありがとうございます。

**Comment by nnn-revo2012** [comment]
rokugaTourokuの方のutil/util.csの漢字コード変更確認しました。ありがとうございます。
問題ないようならこのIssueは数日中にcloseいたします。

既にご存じかもしれませんが、来週(12/16～12/17)にかけてFlashプレーヤー終了、視聴ページデザイン変更、APIの変更などがあるようなので気を付けてください。

[【事前予告】12月17日にN Airの必須バージョンアップを実施します](http://blog.nicovideo.jp/niconews/144589.html)
[【告知】番組視聴ページのデザインを変更します【PC版ニコニコ生放送】](http://blog.nicovideo.jp/niconews/144510.html)
[（12/8追記）【告知】Flash版プレーヤーの提供終了について【PC版ニコニコ生放送】](http://blog.nicovideo.jp/niconews/143015.html)

**Comment by guest-nico** [comment]
ご確認いただきありがとうございます。お手数をおかけしてしまい申し訳ありませんでした。
また、変更についての情報をいただきありがとうございます。
まだどのような影響が出るかは分かりませんが、そちらの時期は動作への影響を確認するようにしたいと思います。
